In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import csv

In [3]:
df = pd.read_csv('/Users/rebekahmclaughlin/Downloads/archive (2)/AviationData.csv', encoding='utf-8')
df.head()

/var/folders/8l/_21d1c153c5ff4j7j3y1l8c80000gn/T/ipykernel_9564/1775512957.py:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/rebekahmclaughlin/Downloads/archive (2)/AviationData.csv', encoding='utf-8')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [5]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [6]:
df['Purpose.of.flight'].value_counts()

Purpose.of.flight
Personal                     49448
Instructional                10601
Unknown                       6802
Aerial Application            4712
Business                      4018
Positioning                   1646
Other Work Use                1264
Ferry                          812
Aerial Observation             794
Public Aircraft                720
Executive/corporate            553
Flight Test                    405
Skydiving                      182
External Load                  123
Public Aircraft - Federal      105
Banner Tow                     101
Air Race show                   99
Public Aircraft - Local         74
Public Aircraft - State         64
Air Race/show                   59
Glider Tow                      53
Firefighting                    40
Air Drop                        11
ASHO                             6
PUBS                             4
PUBL                             1
Name: count, dtype: int64

In [7]:
df['Event.Date'] = pd.to_datetime(df['Event.Date'], yearfirst=True)

In [8]:
df2000 = df.loc[df['Event.Date'] >= '2000-01-01']

In [9]:
df2000incidents = df2000.loc[df['Investigation.Type'] == 'Incident']

In [10]:
df2000incidents['Total.Fatal.Injuries'].value_counts()

Total.Fatal.Injuries
0.0    1726
1.0       5
3.0       1
Name: count, dtype: int64

In [11]:
df2000incidents.loc[df2000incidents['Total.Fatal.Injuries'] > 0]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
51223,20080415X00478,Incident,ENG01RA005,2001-08-05,"Narsarsuaq, Greenland",Greenland,NaN,NaN,NaN,NaN,...,Business,NaN,3.0,NaN,NaN,NaN,NaN,NaN,Foreign,15-04-2008
51490,20040914X01415,Incident,ENG01RA010,2001-09-15,"BELO HORIZONTE, BRAZIL",Brazil,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,3.0,78.0,VMC,NaN,Foreign,15-04-2008
56639,20040611X00786,Incident,FTW04IA147,2004-05-11,"SMI-28, GM",United States,28.886944,-92.142222,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,VMC,Standing,Probable Cause,07-07-2005
60756,20060605X00682,Incident,DFW06IA145,2006-05-30,"Grand Isle 43AA, GM",United States,29.041389,-89.855278,43AA,"Grand Isle, Gulf of Mexico",...,Positioning,NaN,1.0,NaN,NaN,NaN,VMC,Standing,Probable Cause,31-10-2006
63235,20070909X01340,Incident,DFW07IA193,2007-08-24,"Colorado City, TX",United States,32.468334,-100.921111,T88,Colorado City Airport,...,Aerial Application,NaN,1.0,NaN,NaN,NaN,VMC,Standing,Probable Cause,28-05-2008
66194,20090413X62630,Incident,ERA09IA240,2009-04-12,"Fort Myers, FL",United States,263210N,0814519W,RSW,Southwest Florida Int'l,...,Personal,WHITE EQUIPMENT LEASING LLC,1.0,0.0,0.0,4.0,VMC,NaN,The pilotâ€™s abnormal heart rhythm resulting in...,25-09-2020

In [12]:
df2000incidents['Report.Status'].value_counts()

Report.Status
Probable Cause                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     435
Foreign                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            208
<br /><br />                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        62
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5
A failure of the nose landing gear end cap due to fatigue. Contributing to the failure were the ineffective inspection and the unknown effect of grain direction on fatigue life.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
The R10/12 controller issued an improper vector and descent clearance to the GII that put the airplane on a coverging flight path with the B737.  Contributing to the incident was the failure of the FAA's training program to correct ongoing controller performance deficiencies before certifying the D10/12 controller to work without immediate supervision.                                                                                                                                                                                                                                                                                                                                   1
An unsecured access door, which departed the helicopter and damaged a main rotor blade and a tail rotor blade. Contributing to the incident was the helicopter's color scheme, which made visual inspection of the door difficult.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
The Cessna 208 pilotâ€™s failure to identify the correct landing runway.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
An in-flight encounter with lightning. Contributing to the incident was the damaged and displaced tailcone bulkhead frame that inhibited the full travel of the elevator during approach.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
The fatigue fracture and liberation of two airfoils from a low pressure turbine stage 5 nozzle segment that impacted and damaged the downstream low pressure stage 5 blades creating an initial imbalance load in the engineâ€™s low pressure turbine rotor sufficient to allow all the low pressure turbine blades to lose radial blade clearance, contact static structure, and to fracture transversely across the airfoil.  The progressive failure of the low pressure rotor caused an increasingly imbalanced load that eventually resulted in the fracture of the oil supply tube that allowed oil to contact hot engine parts and smolder and ignite resulting in the undercowl fire.\r\n      1
Name: count, Length: 442, dtype: int64

In [13]:
amateurs = df['Amateur.Built'].value_counts()
amateurs

Amateur.Built
No     80312
Yes     8475
Name: count, dtype: int64

In [14]:
amateurs[1] / amateurs[0]

/var/folders/8l/_21d1c153c5ff4j7j3y1l8c80000gn/T/ipykernel_9564/2189823805.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  amateurs[1] / amateurs[0]

0.10552594879968125

In [15]:
amateur = df.loc[df['Amateur.Built'] == 'Yes']

In [16]:
amateur

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
45,20020917X02423,Accident,MKC82DA016,1982-01-06,"ROLLA, MO",United States,NaN,NaN,K07,DOWNTOWN,...,Executive/corporate,NaN,0.0,0.0,0.0,3.0,VMC,Approach,Probable Cause,06-01-1983
73,20020917X02289,Accident,LAX82FUG05,1982-01-10,"UPLAND, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,10-01-1983
99,20020917X02306,Accident,LAX82FUQ08,1982-01-17,"MOJAVE, CA",United States,NaN,NaN,MHV,MOJANE,...,Personal,NaN,1.0,0.0,0.0,0.0,VMC,Maneuvering,Probable Cause,17-01-1983
124,20020917X02296,Accident,LAX82FUJ26,1982-01-19,"KINGMAN, AZ",United States,NaN,NaN,IGM,MOJANE,...,Personal,NaN,0.0,0.0,1.0,0.0,VMC,Climb,Probable Cause,19-01-1983
143,20020917X01762,Accident,ATL82FLT02,1982-01-21,"NEW ALBANY, MS",United States,NaN,NaN,NaN,NEW ALBANY,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,21-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88744,20221109106267,Accident,ERA23LA053,2022-11-02,"STATESBORO, GA",United States,322613N,0814747W,TBR,Statesboro-Bulloch County Airp,...,Personal,BLUESKYS INC,0.0,0.0,1.0,0.0,VMC,NaN,NaN,20-12-2022
88754,20221117106305,Accident,ERA23LA063,2022-11-04,"JASPER, GA",United States,342717N,0842729W,JZP,Pickens County Airport,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,22-11-2022
88812,20221123106352,Accident,WPR23FA044,2022-11-22,"Banning, CA",United States,335543N,1165011W,BNG,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,VMC,NaN,NaN,14-12-2022
88831,20221202106403,Accident,WPR23LA052,2022-11-27,"Mountain Green, UT",United States,041116N,1113657W,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,13-12-2022
88835,20221130106386,Accident,WPR23FA047,2022-11-30,"Torrance, CA",United States,334827N,1182050W,TOA,ZAMPERINI FLD,...,Personal,NaN,2.0,0.0,0.0,0.0,VMC,NaN,NaN,14-12-2022

In [17]:
amateur['Report.Status'].value_counts()

Report.Status
Probable Cause                                                                                                                                                                                                                                                                                            5563
Foreign                                                                                                                                                                                                                                                                                                     68
Factual                                                                                                                                                                                                                                                                                                     14
The pilot's failure to maintain directional control during landing.                                                                                                                                                                                                                                          9
A total loss of engine power for undetermined reasons.                                                                                                                                                                                                                                                       7
                                                                                                                                                                                                                                                                                                          ...
A total loss of engine power during the takeoff climb for undetermined reasons.                                                                                                                                                                                                                              1
The pilot/builderâ€™s inadequate installation of a nosewheel steering component, which resulted in a shimmy and a loss of directional control during the takeoff roll.                                                                                                                                         1
The pilotâ€™s inadequate preflight planning, in that he did not determine whether the airplaneâ€™s climb performance would be sufficient to clear obstacles before initiating take off.                                                                                                                          1
The pilot's inadequate clearance from unmarked power lines while on approach to land at a private airport.                                                                                                                                                                                                   1
The pilotâ€™s failure to secure the magneto switch before attempting to hand rotate the engine which resulted in an inadvertent engine start, a runaway airplane, and subsequent impact with parked airplanes. Contributing to the accident was the failure to properly secure the airplane with chocks.       1
Name: count, Length: 2402, dtype: int64

In [18]:
amateur['Total.Fatal.Injuries'].value_counts()

Total.Fatal.Injuries
0.0     4943
1.0     1714
2.0      576
3.0       39
4.0       14
7.0        4
5.0        4
6.0        2
8.0        1
35.0       1
18.0       1
Name: count, dtype: int64

In [19]:
amateur.loc[amateur['Total.Fatal.Injuries'] == 35.0]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
41728,20001208X07895,Accident,DCA97WA045,1997-05-08,"SHENZHEN, China",China,NaN,NaN,NaN,NaN,...,Unknown,NaN,35.0,NaN,NaN,NaN,UNK,NaN,Foreign,NaN

In [20]:
df2000.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41214 entries, 47675 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                41214 non-null  object
 1   Investigation.Type      41214 non-null  object
 2   Accident.Number         41214 non-null  object
 3   Event.Date              41214 non-null  datetime64[ns]
 4   Location                41198 non-null  object
 5   Country                 41198 non-null  object
 6   Latitude                34359 non-null  object
 7   Longitude               34350 non-null  object
 8   Airport.Code            24931 non-null  object
 9   Airport.Name            25301 non-null  object
 10  Injury.Severity         40214 non-null  object
 11  Aircraft.damage         39146 non-null  object
 12  Aircraft.Category       28406 non-null  object
 13  Registration.Number     40096 non-null  object
 14  Make                    41159 non-null  object
 15  Model                   41146 non-null  object
 16  Amateur.Built           41114 non-null  object
 17  Number.of.Engines       36267 non-null  float64
 18  Engine.Type             34135 non-null  object
 19  FAR.Description         28142 non-null  object
 20  Schedule                4656 non-null   object
 21  Purpose.of.flight       35122 non-null  object
 22  Air.carrier             14085 non-null  object
 23  Total.Fatal.Injuries    30131 non-null  float64
 24  Total.Serious.Injuries  29120 non-null  float64
 25  Total.Minor.Injuries    29701 non-null  float64
 26  Total.Uninjured         35574 non-null  float64
 27  Weather.Condition       36747 non-null  object
 28  Broad.phase.of.flight   14953 non-null  object
 29  Report.Status           34830 non-null  object
 30  Publication.Date        39999 non-null  object
dtypes: datetime64[ns](1), float64(5), object(25)
memory usage: 10.1+ MB

In [21]:
df2000['Injury.Severity'].value_counts()[:30]

Injury.Severity
Non-Fatal      30457
Fatal           5262
Fatal(1)        1646
Fatal(2)        1005
Incident         643
Fatal(3)         329
Minor            218
Fatal(4)         197
Serious          173
Fatal(5)          76
Fatal(6)          46
Unavailable       43
Fatal(7)          16
Fatal(10)         13
Fatal(8)          12
Fatal(9)           7
Fatal(11)          4
Fatal(14)          3
Fatal(13)          3
Fatal(19)          3
Fatal(20)          3
Fatal(71)          2
Fatal(46)          2
Fatal(118)         2
Fatal(92)          2
Fatal(154)         2
Fatal(23)          2
Fatal(24)          2
Fatal(113)         2
Fatal(102)         2
Name: count, dtype: int64

In [22]:
seriousinjuries = df2000.loc[df2000['Injury.Severity'] == 'Serious']

In [23]:
seriousinjuries['Amateur.Built']

87307    No
87316    No
87322    No
87325    No
87334    No
         ..
88827    No
88855    No
88866    No
88872    No
88875    No
Name: Amateur.Built, Length: 173, dtype: object

In [24]:
df['Aircraft.Category'].value_counts()

Aircraft.Category
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

In [25]:
df['Injury.Severity'].value_counts()[:30]

Injury.Severity
Non-Fatal      67357
Fatal(1)        6167
Fatal           5262
Fatal(2)        3711
Incident        2219
Fatal(3)        1147
Fatal(4)         812
Fatal(5)         235
Minor            218
Serious          173
Fatal(6)         161
Unavailable       96
Fatal(7)          56
Fatal(8)          51
Fatal(10)         32
Fatal(9)          18
Fatal(14)         11
Fatal(11)         10
Fatal(13)          9
Fatal(12)          8
Fatal(18)          5
Fatal(20)          5
Fatal(15)          5
Fatal(25)          4
Fatal(23)          4
Fatal(19)          3
Fatal(16)          3
Fatal(34)          3
Fatal(17)          3
Fatal(104)         2
Name: count, dtype: int64

In [26]:
statusunavail = df.loc[df['Injury.Severity'] == 'Unavailable']

In [27]:
statusunavail['Report.Status'].value_counts()

Report.Status
Foreign           81
Factual           10
Probable Cause     5
Name: count, dtype: int64

In [28]:
statusunavail['Aircraft.damage'].value_counts()

Aircraft.damage
Substantial    59
Destroyed      27
Minor           3
Name: count, dtype: int64

In [29]:
df['Aircraft.damage'].value_counts()

Aircraft.damage
Substantial    64148
Destroyed      18623
Minor           2805
Unknown          119
Name: count, dtype: int64

In [30]:
unknowndamage = df.loc[df['Aircraft.damage'] == 'Unknown']

In [31]:
unknowndamage.isna().sum()

Event.Id                    0
Investigation.Type          0
Accident.Number             0
Event.Date                  0
Location                    0
Country                     0
Latitude                   51
Longitude                  51
Airport.Code               71
Airport.Name               87
Injury.Severity            27
Aircraft.damage             0
Aircraft.Category           0
Registration.Number         0
Make                        0
Model                       0
Amateur.Built               0
Number.of.Engines          58
Engine.Type               113
FAR.Description             0
Schedule                  114
Purpose.of.flight          67
Air.carrier                79
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Minor.Injuries        0
Total.Uninjured             0
Weather.Condition          77
Broad.phase.of.flight     119
Report.Status             112
Publication.Date           67
dtype: int64

In [32]:
unknowndamage['Report.Status'].value_counts()

Report.Status
The pilotâ€™s failure to extend the landing gear before landing. \r\n                                                                                                                                                 2
The pilotâ€™s failure to maintain proper airspeed on approach and his attempt to land on a wet runway with insufficient runway remaining, resulting in an overrun and loss of directional control.\r\n\r\n            1
The pilotâ€™s failure to maintain proper airspeed on approach resulting in an extended touchdown, bounced landing, and runway excursion.\r\n\r\n                                                                      1
The loss of engine power for undetermined reasons based on available evidence. \r\n                                                                                                                                 1
A loss of engine power for reasons that could not be determined due to a lack of available evidence. \r\n                                                                                                           1
The student pilotâ€™s excessive pitch during takeoff resulted in a loss of control and impact with terrain. Contributing was the studentâ€™s failure to relinquish the controls when ordered by the instructor. \r\n    1
Name: count, dtype: int64

In [33]:
unknowndamage['Injury.Severity'].value_counts()

Injury.Severity
Non-Fatal    60
Fatal        24
Minor         4
Serious       4
Name: count, dtype: int64

In [34]:
unknowndamage['Total.Fatal.Injuries'].value_counts()

Total.Fatal.Injuries
0.0     96
1.0     12
2.0      5
3.0      3
4.0      1
7.0      1
14.0     1
Name: count, dtype: int64

In [35]:
df['FAR.Description'].value_counts()

FAR.Description
091                               18221
Part 91: General Aviation          6486
NUSN                               1584
NUSC                               1013
137                                1010
135                                 746
121                                 679
Part 137: Agricultural              437
UNK                                 371
Part 135: Air Taxi & Commuter       298
PUBU                                253
129                                 246
Part 121: Air Carrier               165
133                                 107
Part 129: Foreign                   100
Non-U.S., Non-Commercial             97
Non-U.S., Commercial                 93
Part 133: Rotorcraft Ext. Load       32
Unknown                              22
Public Use                           19
091K                                 14
ARMF                                  8
Part 125: 20+ Pax,6000+ lbs           5
125                                   5
107                                   4
Public Aircraft                       2
103                                   2
Part 91 Subpart K: Fractional         1
Armed Forces                          1
Part 91F: Special Flt Ops.            1
437                                   1
Name: count, dtype: int64

In [36]:
newdf = df.drop(df[df['Amateur.Built'] == 'Yes'].index)

In [37]:
newdf = newdf.drop(columns=['Amateur.Built'])

In [38]:
newdf = newdf.loc[df['Event.Date'] >= '2000-01-01']

In [39]:
newdf

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
47675,20001212X20407,Accident,MIA00LA063,2000-01-01,"HOMESTEAD, FL",United States,NaN,NaN,NaN,NaN,...,Positioning,NaN,0.0,0.0,0.0,3.0,VMC,Cruise,Probable Cause,29-11-2000
47676,20001212X20327,Accident,ATL00FA019,2000-01-01,"MONTEAGLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,19-04-2001
47677,20001212X20383,Accident,LAX00LA063,2000-01-02,"VICTORVILLE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Cruise,Probable Cause,04-12-2000
47678,20001212X20382,Accident,LAX00LA062,2000-01-02,"DOS PALOS, CA",United States,NaN,NaN,NaN,NaN,...,Instructional,NaN,0.0,0.0,1.0,0.0,VMC,Cruise,Probable Cause,14-12-2001
47679,20001212X20364,Accident,FTW00LA067,2000-01-02,"CORNING, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,5.0,VMC,Cruise,Probable Cause,02-03-2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [40]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36542 entries, 47675 to 88888
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                36542 non-null  object
 1   Investigation.Type      36542 non-null  object
 2   Accident.Number         36542 non-null  object
 3   Event.Date              36542 non-null  datetime64[ns]
 4   Location                36526 non-null  object
 5   Country                 36526 non-null  object
 6   Latitude                30178 non-null  object
 7   Longitude               30172 non-null  object
 8   Airport.Code            21786 non-null  object
 9   Airport.Name            22114 non-null  object
 10  Injury.Severity         35543 non-null  object
 11  Aircraft.damage         34484 non-null  object
 12  Aircraft.Category       25128 non-null  object
 13  Registration.Number     35487 non-null  object
 14  Make                    36495 non-null  object
 15  Model                   36476 non-null  object
 16  Number.of.Engines       31825 non-null  float64
 17  Engine.Type             29796 non-null  object
 18  FAR.Description         24885 non-null  object
 19  Schedule                4620 non-null   object
 20  Purpose.of.flight       30504 non-null  object
 21  Air.carrier             13102 non-null  object
 22  Total.Fatal.Injuries    26618 non-null  float64
 23  Total.Serious.Injuries  25756 non-null  float64
 24  Total.Minor.Injuries    26286 non-null  float64
 25  Total.Uninjured         31834 non-null  float64
 26  Weather.Condition       32154 non-null  object
 27  Broad.phase.of.flight   13137 non-null  object
 28  Report.Status           30506 non-null  object
 29  Publication.Date        35356 non-null  object
dtypes: datetime64[ns](1), float64(5), object(24)
memory usage: 8.6+ MB

In [41]:
newdf['Aircraft.Category'].value_counts()

Aircraft.Category
Airplane             21204
Helicopter            2989
Glider                 433
Balloon                199
Weight-Shift           139
Powered Parachute       83
Gyrocraft               31
Ultralight              18
Unknown                 11
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
Name: count, dtype: int64

In [42]:
newdf['Aircraft.Category'].isna().sum()

11414

In [43]:
newdf.loc[newdf['Aircraft.Category'] == 'Unknown']

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
68242,20100627X20107,Accident,CEN10RA345,2010-06-01,"Campeche, Mexico",Mexico,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,13.0,NaN,NaN,NaN,25-09-2020
74960,20140421X23520,Accident,CEN14WA206,2014-04-20,"Jamijarvi, Finland",Finland,006160N,0023120E,NaN,NaN,...,NaN,NaN,7.0,4.0,0.0,0.0,NaN,NaN,<br /><br />,03-11-2020
75574,20140923X35458,Accident,CEN14WA516,2014-08-09,"Stockerau, Austria",Austria,482433N,0161128E,LOAU,Stockerau Airport,...,NaN,NaN,0.0,2.0,0.0,0.0,VMC,NaN,NaN,25-09-2020
75689,20140902X43845,Incident,CEN14WA473,2014-08-28,"Geneva, Eswatini",Eswatini,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,25-09-2020
75724,20140905X04621,Accident,CEN14WA484,2014-09-05,"Samso, Denmark",Denmark,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,25-09-2020
75833,20140923X65822,Accident,CEN14WA518,2014-09-23,"Tempsford, United Kingdom, United Kingdom",United Kingdom,521020N,0001657E,NaN,NaN,...,NaN,NaN,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN
75843,20141002X22321,Accident,CEN14WA529,2014-09-25,"Suchitepequez Department, Guatemala",Guatemala,NaN,NaN,NaN,NaN,...,NaN,Not Provided,0.0,0.0,0.0,0.0,NaN,NaN,NaN,25-09-2020
77773,20160120X82009,Incident,CEN16IA091,2016-01-12,"Little Rock, AR",United States,344346N,0921329W,LIT,BILL AND HILLARY CLINTON NATIO,...,NaN,CENTRAL FLYING SERVICE INC,0.0,0.0,0.0,4.0,VMC,NaN,The flight crew's inadequate preflight inspect...,25-09-2020
82717,20190213X90627,Accident,ANC19WA013,2018-12-30,"Ulan-Ude, Russia",Russia,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,0.0,0.0,0.0,NaN,NaN,NaN,26-09-2020
85071,20210706103424,Accident,GAA20WA148,2020-07-19,"Juta, Hungary",Hungary,NaN,NaN,LHKV,NaN,...,NaN,NaN,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
85466,20201009102120,Accident,WPR21LA011,2020-10-06,"Spirit Lake, ID",United States,475849N,1164711W,ID22,Treeport Airport,...,Personal,NaN,1.0,1.0,0.0,0.0,VMC,NaN,NaN,03-11-2020

In [44]:
newdf['Model'].value_counts()

Model
172             889
152             534
737             477
172N            415
172S            372
               ...
E-33C             1
Combo FC 912      1
382G-44K-30       1
SGS 1-35C         1
GLASAIR           1
Name: count, Length: 5724, dtype: int64

In [45]:
df.describe()

,Event.Date,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,88889,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1999-09-17 17:13:39.354475904,1.146585,0.647855,0.279881,0.357061,5.325440
min,1948-10-24 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1989-01-15 00:00:00,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1998-07-18 00:00:00,1.000000,0.000000,0.000000,0.000000,1.000000
75%,2009-07-01 00:00:00,1.000000,0.000000,0.000000,0.000000,2.000000
max,2022-12-29 00:00:00,8.000000,349.000000,161.000000,380.000000,699.000000
std,NaN,0.446510,5.485960,1.544084,2.235625,27.913634

In [46]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36542 entries, 47675 to 88888
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                36542 non-null  object
 1   Investigation.Type      36542 non-null  object
 2   Accident.Number         36542 non-null  object
 3   Event.Date              36542 non-null  datetime64[ns]
 4   Location                36526 non-null  object
 5   Country                 36526 non-null  object
 6   Latitude                30178 non-null  object
 7   Longitude               30172 non-null  object
 8   Airport.Code            21786 non-null  object
 9   Airport.Name            22114 non-null  object
 10  Injury.Severity         35543 non-null  object
 11  Aircraft.damage         34484 non-null  object
 12  Aircraft.Category       25128 non-null  object
 13  Registration.Number     35487 non-null  object
 14  Make                    36495 non-null  object
 15  Model                   36476 non-null  object
 16  Number.of.Engines       31825 non-null  float64
 17  Engine.Type             29796 non-null  object
 18  FAR.Description         24885 non-null  object
 19  Schedule                4620 non-null   object
 20  Purpose.of.flight       30504 non-null  object
 21  Air.carrier             13102 non-null  object
 22  Total.Fatal.Injuries    26618 non-null  float64
 23  Total.Serious.Injuries  25756 non-null  float64
 24  Total.Minor.Injuries    26286 non-null  float64
 25  Total.Uninjured         31834 non-null  float64
 26  Weather.Condition       32154 non-null  object
 27  Broad.phase.of.flight   13137 non-null  object
 28  Report.Status           30506 non-null  object
 29  Publication.Date        35356 non-null  object
dtypes: datetime64[ns](1), float64(5), object(24)
memory usage: 8.6+ MB

In [47]:
newdf['Aircraft.Category'].value_counts()

Aircraft.Category
Airplane             21204
Helicopter            2989
Glider                 433
Balloon                199
Weight-Shift           139
Powered Parachute       83
Gyrocraft               31
Ultralight              18
Unknown                 11
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
Name: count, dtype: int64

In [48]:
newdf['Aircraft.Category']

47675         NaN
47676         NaN
47677         NaN
47678         NaN
47679         NaN
           ...
88884         NaN
88885         NaN
88886    Airplane
88887         NaN
88888         NaN
Name: Aircraft.Category, Length: 36542, dtype: object

In [49]:
newdf.head(30)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
47675,20001212X20407,Accident,MIA00LA063,2000-01-01,"HOMESTEAD, FL",United States,NaN,NaN,NaN,NaN,...,Positioning,NaN,0.0,0.0,0.0,3.0,VMC,Cruise,Probable Cause,29-11-2000
47676,20001212X20327,Accident,ATL00FA019,2000-01-01,"MONTEAGLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,19-04-2001
47677,20001212X20383,Accident,LAX00LA063,2000-01-02,"VICTORVILLE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Cruise,Probable Cause,04-12-2000
47678,20001212X20382,Accident,LAX00LA062,2000-01-02,"DOS PALOS, CA",United States,NaN,NaN,NaN,NaN,...,Instructional,NaN,0.0,0.0,1.0,0.0,VMC,Cruise,Probable Cause,14-12-2001
47679,20001212X20364,Accident,FTW00LA067,2000-01-02,"CORNING, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,5.0,VMC,Cruise,Probable Cause,02-03-2001
47680,20001212X20358,Accident,FTW00LA057,2000-01-02,"ODESSA, TX",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Climb,Probable Cause,02-03-2001
47681,20001212X20344,Accident,DEN00FA037,2000-01-02,"TELLURIDE, CO",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Climb,Probable Cause,19-04-2001
47682,20001212X20342,Incident,DCA00WA018,2000-01-02,"AMSTERDAM, Netherlands",Netherlands,NaN,NaN,NaN,NaN,...,Unknown,NaN,NaN,NaN,NaN,143.0,UNK,NaN,Foreign,NaN
47683,20001212X20402,Accident,MIA00FA060,2000-01-03,CAYEY,NaN,NaN,NaN,NaN,NaN,...,Unknown,NaN,0.0,0.0,0.0,4.0,VMC,Cruise,Probable Cause,17-07-2001
47684,20001212X20359,Accident,FTW00LA058,2000-01-03,"HOUSTON, TX",United States,NaN,NaN,T02,CLOVER FIELD,...,Personal,NaN,0.0,0.0,0.0,4.0,VMC,Climb,Probable Cause,02-07-2001
47685,20001212X20328,Accident,ATL00FA021,2000-01-03,"CORDESVILLE, SC",United States,NaN,NaN,5OJ,MONCKS CORNER AIRPORT,...,Personal,NaN,2.0,1.0,0.0,0.0,VMC,Approach,Probable Cause,19-04-2001
47688,20001212X20346,Accident,DEN00LA036,2000-01-04,"JACKSON, WY",United States,NaN,NaN,JAC,JACKSON HOLE AIRPORT,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Landing,Probable Cause,29-11-2000
47689,20001212X20403,Accident,MIA00FA064,2000-01-05,ATLANTIC OCEAN,ATLANTIC OCEAN,NaN,NaN,NaN,NaN,...,Instructional,NaN,1.0,0.0,0.0,0.0,VMC,Descent,Probable Cause,29-11-2000
47690,20001212X20377,Accident,IAD00LA015,2000-01-05,"BRUTUS, NY",United States,NaN,NaN,NaN,NaN,...,Aerial Observation,NaN,0.0,0.0,0.0,4.0,VMC,Maneuvering,Probable Cause,04-12-2000
47691,20001212X20421,Accident,NYC00FA063,2000-01-06,"OLD FORGE, PA",United States,NaN,NaN,AVP,WILKES-BARRE/SCRANTON,...,Instructional,NaN,2.0,0.0,0.0,0.0,VMC,Approach,Probable Cause,02-03-2001
47692,20001212X20330,Accident,CHI00FA057,2000-01-06,"DUNBAR, WI",United States,NaN,NaN,IMT,FORD AIRPORT,...,Positioning,NaN,1.0,0.0,0.0,0.0,VMC,Approach,Probable Cause,22-05-2001
47693,20001212X20429,Accident,SEA00FA037,2000-01-07,"MARYSVILLE, WA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,VMC,Climb,Probable Cause,09-05-2001
47694,20001212X20385,Accident,LAX00LA069,2000-01-07,"RIALTO, CA",United States,NaN,NaN,L67,RIALTO,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Cruise,Probable Cause,10-07-2001
47695,20001212X20425,Accident,NYC00LA065,2000-01-08,"HARPSWELL, ME",United States,NaN,NaN,ME33,FARR FIELD AIRPOT,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,29-11-2000
47696,20001212X20386,Accident,LAX00LA070,2000-01-08,"CHINO, CA",United States,NaN,NaN,CNO,CHINO,...,Ferry,NaN,0.0,1.0,0.0,0.0,VMC,Approach,Probable Cause,19-04-2001
47697,20001212X20350,Accident,DEN00LA041,2000-01-08,"HUNTSVILLE, UT",United States,NaN,NaN,NaN,NaN,...,Instructional,NaN,0.0,0.0,0.0,2.0,IMC,Maneuvering,Probable Cause,04-12-2000
47698,20001212X20349,Accident,DEN00LA040,2000-01-08,"PUEBLO, CO",United States,NaN,NaN,PUB,PUEBLO MEMORIAL,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Landing,Probable Cause,29-11-2000
47699,20001212X20347,Accident,DEN00LA038,2000-01-08,"ROCK SPRINGS, WY",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,1.0,IMC,Cruise,Probable Cause,29-11-2000
47701,20001212X20329,Accident,ATL00FA023,2000-01-08,"MACON, GA",United States,NaN,NaN,MAC,HERBERT SMART DOWNTOWN,...,Personal,NaN,2.0,0.0,0.0,0.0,VMC,Cruise,Probable Cause,25-04-2001
47703,20001212X20378,Accident,IAD00LA016,2000-01-09,"WAYNESBURG, PA",United States,NaN,NaN,WAY,GREENE COUNTY AIRPORT,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Landing,Probable Cause,08-05-2001
47704,20001212X20360,Accident,FTW00LA059,2000-01-09,"SWEENEY, TX",United States,NaN,NaN,NaN,NaN,...,Instructional,NaN,0.0,0.0,0.0,2.0,VMC,Cruise,Probable Cause,18-01-2001
47706,20001212X20404,Accident,MIA00FA066,2000-01-09,"MOUNT PLEASANT, SC",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Maneuvering,Probable Cause,29-11-2000
47707,20001212X20348,Accident,DEN00LA039,2000-01-09,"ALBUQUERQUE, NM",United States,NaN,NaN,4AC,CORONADO AIRPORT,...,Personal,NaN,0.0,1.0,0.0,2.0,VMC,Standing,Probable Cause,30-09-2003
47708,20001212X20432,Accident,SEA00LA036,2000-01-10,"EVERETT, WA",United States,NaN,NaN,PAE,SNOHOMISH COUNTY,...,Positioning,NaN,0.0,0.0,0.0,1.0,IMC,Takeoff,Probable Cause,18-01-2001
47709,20001212X20362,Accident,FTW00LA061,2000-01-10,"SHERMAN, TX",United States,NaN,NaN,NONE,FLYING M,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,18-01-2001

In [50]:
newdf['Purpose.of.flight'].value_counts()

Purpose.of.flight
Personal                     18468
Instructional                 4741
Aerial Application            1759
Business                      1075
Positioning                    886
Unknown                        789
Other Work Use                 642
Aerial Observation             431
Public Aircraft                249
Flight Test                    245
Ferry                          191
Executive/corporate            191
Skydiving                      148
External Load                  122
Public Aircraft - Federal      104
Banner Tow                     101
Public Aircraft - Local         74
Air Race show                   71
Public Aircraft - State         64
Glider Tow                      53
Firefighting                    40
Air Race/show                   39
Air Drop                        11
ASHO                             5
PUBS                             4
PUBL                             1
Name: count, dtype: int64

In [51]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Balloon'].index)

In [52]:
newdf['Aircraft.Category'].value_counts()

Aircraft.Category
Airplane             21204
Helicopter            2989
Glider                 433
Weight-Shift           139
Powered Parachute       83
Gyrocraft               31
Ultralight              18
Unknown                 11
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
Name: count, dtype: int64

In [53]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Glider'].index)

In [54]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Weight-Shift'].index)

In [55]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Powered Parachute'].index)

In [56]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Gyrocraft'].index)

In [57]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Ultralight'].index)

In [58]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'WSFT'].index)

In [59]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Powered-Lift'].index)

In [60]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Blimp'].index)

In [61]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'UNK'].index)

In [62]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Rocket'].index)

In [63]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35618 entries, 47675 to 88888
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                35618 non-null  object
 1   Investigation.Type      35618 non-null  object
 2   Accident.Number         35618 non-null  object
 3   Event.Date              35618 non-null  datetime64[ns]
 4   Location                35602 non-null  object
 5   Country                 35602 non-null  object
 6   Latitude                29264 non-null  object
 7   Longitude               29258 non-null  object
 8   Airport.Code            21285 non-null  object
 9   Airport.Name            21599 non-null  object
 10  Injury.Severity         34621 non-null  object
 11  Aircraft.damage         33657 non-null  object
 12  Aircraft.Category       24204 non-null  object
 13  Registration.Number     34565 non-null  object
 14  Make                    35571 non-null  object
 15  Model                   35552 non-null  object
 16  Number.of.Engines       31056 non-null  float64
 17  Engine.Type             29470 non-null  object
 18  FAR.Description         23966 non-null  object
 19  Schedule                4598 non-null   object
 20  Purpose.of.flight       29598 non-null  object
 21  Air.carrier             12704 non-null  object
 22  Total.Fatal.Injuries    25831 non-null  float64
 23  Total.Serious.Injuries  24927 non-null  float64
 24  Total.Minor.Injuries    25465 non-null  float64
 25  Total.Uninjured         30948 non-null  float64
 26  Weather.Condition       31266 non-null  object
 27  Broad.phase.of.flight   12998 non-null  object
 28  Report.Status           29678 non-null  object
 29  Publication.Date        34453 non-null  object
dtypes: datetime64[ns](1), float64(5), object(24)
memory usage: 8.4+ MB

In [64]:
newdf = newdf.drop(newdf[newdf['Aircraft.Category'] == 'Helicopter'].index)

In [65]:
newdf.describe()

,Event.Date,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,32629,28575.000000,23193.000000,22279.000000,22772.000000,28074.000000
mean,2010-06-13 20:28:46.905513472,1.180822,0.987324,0.397145,0.345600,8.101482
min,2000-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2004-07-04 00:00:00,1.000000,0.000000,0.000000,0.000000,0.000000
50%,2009-09-30 00:00:00,1.000000,0.000000,0.000000,0.000000,1.000000
75%,2016-05-14 00:00:00,1.000000,1.000000,0.000000,0.000000,2.000000
max,2022-12-29 00:00:00,8.000000,295.000000,161.000000,84.000000,576.000000
std,NaN,0.440984,7.443249,2.377212,1.335413,35.089870

In [66]:
newdf['Broad.phase.of.flight'].value_counts()

Broad.phase.of.flight
Landing        3648
Takeoff        2363
Cruise         1943
Maneuvering    1518
Approach       1299
Taxi            465
Descent         384
Climb           382
Go-around       299
Standing        243
Unknown          65
Other            19
Name: count, dtype: int64

In [67]:
unknownflightphase = newdf.loc[newdf['Broad.phase.of.flight'] == 'Unknown']

In [68]:
unknownflightphase['Report.Status'].value_counts()

Report.Status
Probable Cause    65
Name: count, dtype: int64

In [69]:
newdf['Make'].isna().sum()

46

In [70]:
newdf['Model'].value_counts()

Model
172               889
152               534
737               477
172N              415
172S              372
                 ...
PA-28-280           1
P92 Super Echo      1
C-172N              1
HK 36 TTC           1
GLASAIR             1
Name: count, Length: 4929, dtype: int64

In [71]:
makelist= list(newdf['Make'].value_counts().index)

In [72]:
makelist

['Cessna',
 'CESSNA',
 'Piper',
 'PIPER',
 'Beech',
 'BOEING',
 'BEECH',
 'Boeing',
 'Bell',
 'Mooney',
 'Robinson',
 'Air Tractor',
 'MOONEY',
 'AIRBUS',
 'CIRRUS DESIGN CORP',
 'AIR TRACTOR INC',
 'Bellanca',
 'BELLANCA',
 'Hughes',
 'Grumman',
 'Mcdonnell Douglas',
 'AERONCA',
 'Maule',
 'MAULE',
 'EMBRAER',
 'Schweizer',
 'Aeronca',
 'De Havilland',
 'Champion',
 'Luscombe',
 'AIR TRACTOR',
 'North American',
 'LUSCOMBE',
 'Stinson',
 'CHAMPION',
 'STINSON',
 'DEHAVILLAND',
 'Aviat',
 'Aero Commander',
 'CIRRUS',
 'NORTH AMERICAN',
 'Airbus Industrie',
 'Taylorcraft',
 'GRUMMAN',
 'Ayres',
 'DIAMOND AIRCRAFT IND INC',
 'AVIAT AIRCRAFT INC',
 'AERO COMMANDER',
 'Cirrus Design Corp.',
 'BOMBARDIER INC',
 'Cirrus',
 'MCDONNELL DOUGLAS',
 'Grumman American',
 'Embraer',
 'SOCATA',
 'TAYLORCRAFT',
 'Aerospatiale',
 'GRUMMAN ACFT ENG COR-SCHWEIZER',
 'Rockwell',
 'RAYTHEON AIRCRAFT COMPANY',
 'ROCKWELL INTERNATIONAL',
 'GRUMMAN AMERICAN AVN. CORP.',
 'Learjet',
 'BOMBARDIER',
 'Eurocopter',
 'AMERICAN CHAMPION AIRCRAFT',
 'Douglas',
 'Grumman-schweizer',
 'FLIGHT DESIGN GMBH',
 'Airbus',
 'Ercoupe',
 'Sikorsky',
 'Enstrom',
 'AYRES CORPORATION',
 'Mitsubishi',
 'Waco',
 'Canadair',
 'Socata',
 'ERCOUPE',
 'MOONEY AIRCRAFT CORP.',
 'Swearingen',
 'COSTRUZIONI AERONAUTICHE TECNA',
 'DE HAVILLAND',
 'DIAMOND',
 'SWEARINGEN',
 'Bombardier',
 'Fairchild',
 'AVIAT',
 'Eurocopter France',
 'Ercoupe (eng & Research Corp.)',
 'FAIRCHILD',
 'Diamond Aircraft Industries',
 'PIPER AIRCRAFT INC',
 'Lake',
 'Pilatus',
 'DOUGLAS',
 'Schleicher',
 'Aerostar',
 'EVEKTOR-AEROTECHNIK AS',
 'LEARJET',
 'Lockheed',
 'Wsk Pzl Mielec',
 'WACO',
 'Yakovlev',
 'RANS',
 'Weatherly',
 'ROCKWELL',
 'Hiller',
 'CESSNA AIRCRAFT CO',
 'GULFSTREAM',
 'Bombardier, Inc.',
 'AYRES',
 'American Champion (acac)',
 'Fokker',
 'AIRBUS INDUSTRIE',
 'Boeing Stearman',
 'QUICKSILVER',
 'BAE',
 'PILATUS',
 'Globe',
 'Ryan',
 'Flight Design',
 'Let',
 'British Aerospace',
 'Beechcraft',
 'CUB CRAFTERS INC',
 'ATR',
 'Helio',
 'Navion',
 'HELIO',
 'Diamond',
 'ROBINSON',
 'Rockwell International',
 'SCHWEIZER AIRCRAFT CORP',
 'CUBCRAFTERS INC',
 'Saab-scania Ab (saab)',
 'Raytheon',
 'Gates Learjet',
 'Raytheon Aircraft Company',
 'GLOBE',
 'AMERICAN LEGEND AIRCRAFT CO',
 'SMITH',
 'CHRISTEN INDUSTRIES INC',
 'Agusta',
 'RYAN',
 'SAAB',
 'Gulfstream Aerospace',
 'NAVION',
 'MITSUBISHI',
 'GREAT LAKES',
 'Stearman',
 'BELL',
 'Christen Industries',
 'ENGINEERING & RESEARCH',
 'RAYTHEON',
 'LAKE',
 'Burkhart Grob',
 'Kaman',
 'AMERICAN',
 'Raytheon Corporate Jets',
 'SILVAIRE',
 'COLUMBIA AIRCRAFT MFG',
 'Schempp-hirth',
 'Britten-norman',
 'CONSOLIDATED AERONAUTICS INC.',
 'HAWKER BEECHCRAFT CORP',
 'GULFSTREAM AEROSPACE',
 'American Aviation',
 'YAKOVLEV',
 'CZECH AIRCRAFT WORKS SPOL SRO',
 'THRUSH AIRCRAFT INC',
 'Dassault Aviation',
 'TEXTRON AVIATION INC',
 'AMERICAN AVIATION',
 'American Champion',
 'REMOS AIRCRAFT GMBH',
 'CURTISS WRIGHT',
 'Israel Aircraft Industries',
 'Extra Flugzeugbau',
 'ALON',
 'TECNAM',
 'BRITTEN NORMAN',
 'Pitts',
 'Cub Crafters',
 'WSK PZL MIELEC',
 'CZECH SPORT AIRCRAFT AS',
 'SIAI-MARCHETTI',
 'LEARJET INC',
 'Smith, Ted Aerostar',
 'LOCKHEED',
 'Great Lakes',
 'EXTRA FLUGZEUGBAU GMBH',
 'AEROPRO CZ',
 'VANS',
 'Aircraft Mfg & Dev. Co. (amd)',
 'MOONEY AIRPLANE CO INC',
 'Mbb',
 'Cirrus Design Corporation',
 'AERO VODOCHODY',
 'Dornier',
 'VANS AIRCRAFT INC',
 'Alon',
 'CESSNA AIRCRAFT',
 'THE BOEING COMPANY',
 'Gulfstream',
 'GULFSTREAM-SCHWEIZER A/C CORP',
 'Gulfstream American',
 'American',
 'JABIRU USA SPORT AIRCRAFT LLC',
 'GULFSTREAM AMERICAN CORP',
 'EMBRAER S A',
 'FLIGHT DESIGN',
 'Cameron Balloons',
 'CESSNA AIRCRAFT COMPANY',
 'Hawker Siddeley',
 'de Havilland',
 'WEATHERLY AVIATION CO INC',
 'PITTS',
 'REPUBLIC',
 'PIPER AIRCRAFT CORPORATION',
 'Aero Vodochody',
 'BOEING COMPANY',
 'Smith',
 'Lancair',
 'TEMCO',
 'AVIAT INC',
 'Balloon Works',
 'GATES LEARJET CORP.',
 'Brantly Helicopter',
 'AEROTEK',
 'Dehavilland',
 'Aerotek',
 'PILATUS AIRCRAFT LTD',
 'Commander',
 'Curtiss-wright',
 'ISRAEL AIRCRAFT INDUSTRIES',
 'PIAGGIO',
 'Hawker Beechcraft',
 'American Champion Aircraft',
 'Dassault',
 'LANCAIR COMPANY',
 'Ayres Corporation',
 'Aero Vodochody Aero. Works',
 'Pipistrel',
 'RYAN AERONAUTICAL',
 'Hawker Beechcraft Corp.',
 'FOKKER',
 'HAWKER',
 'DORNIER',
 'American Aviation Corp. (aac)',
 'UNIVERSAL STINSON',
 'Siai-marchetti',
 'Sukhoi',
 'WEATHERLY',
 'HAWKER BEECHCRAFT',
 'WACO CLASSIC AIRCRAFT',
 'American General Aircraft',
 'DIAMOND AIRCRAFT IND GMBH',
 'JABIRU',
 'Pzl-mielec',
 'Gulfstream-schweizer',
 'LIBERTY AEROSPACE INCORPORATED',
 'Casa',
 'DASSAULT',
 'SIKORSKY',
 'Republic',
 'Reims Aviation',
 'CUB CRAFTERS',
 'SHORT BROS',
 'Czech Aircraft Works',
 'Garlick',
 'Air Tractor Inc.',
 'SUKHOI',
 'EMBRAER-EMPRESA BRASILEIRA DE',
 'Short Brothers',
 'Convair',
 'FLEET',
 'MCDONNELL DOUGLAS AIRCRAFT CO',
 'LANCAIR',
 'ANTONOV',
 'Grumman-Schweizer',
 'Saab',
 'EXTRA',
 'SCHWEIZER',
 'Quicksilver',
 'QUEST AIRCRAFT COMPANY LLC',
 'CANADAIR',
 'Robinson Helicopter Company',
 'NANCHANG CHINA',
 'Convair Div. Of Gen. Dynamics',
 'NEW PIPER AIRCRAFT INC',
 'EUROCOPTER',
 'TL ULTRALIGHT SRO',
 'American Legend',
 'Cirrus Design Corp',
 'Aviat Aircraft Inc',
 'Liberty Aerospace Inc.',
 'ECLIPSE AVIATION CORP',
 'GATES LEAR JET',
 'Fairchild Swearingen',
 'Reims',
 'ZENITH',
 'TAYLORCRAFT AVIATION CORP',
 'ARION AIRCRAFT LLC',
 'REMOS ACFT GMBH FLUGZEUGBAU',
 'Fairchild Hiller',
 'FANTASY AIR SRO',
 'Vans',
 'Eurocopter Deutschland',
 'Temco',
 'Extra',
 'Raven',
 'SHORT BROS. & HARLAND',
 'BRITTEN-NORMAN',
 'Fleet',
 'Consolidated Aeronautics Inc.',
 'CLASSIC AIRCRAFT CORP',
 'GENERAL ATOMICS',
 'Zenair',
 'QUAD CITY',
 'Interstate',
 'Grob',
 'Culver',
 'BEECHCRAFT',
 'BRITISH AEROSPACE',
 'Snow',
 'MEYERS',
 'STEARMAN AIRCRAFT',
 'Dassault-breguet',
 'ROBIN',
 'HAWKER SIDDELEY',
 'THRUSH',
 'American Champion (ACAC)',
 'Flight Design Gmbh',
 'Burkhart Grob Flugzeugbau',
 'EXTRA FLUGZEUGPRODUKTIONS-UND',
 'CIRRUS DESIGN CORP.',
 'AIRCRAFT MFG & DEVELOPMENT CO',
 'Pzl-bielsko',
 'Curtis-wright',
 'Cirrus Design',
 'Engineering & Research',
 'PIPER AIRCRAFT',
 'ZLIN',
 'PZL MIELEC',
 'CONSOLIDATED VULTEE',
 'Nanchang',
 'AERO SP Z O O',
 'Quest',
 'Ercoupe (Eng & Research Corp.)',
 'Textron Aviation',
 'STEARMAN',
 'AEROVODOCHODY',
 'REIMS',
 'Porterfield',
 'PARTENAVIA',
 'EAGLE',
 'Scottish Aviation',
 'Monocoupe',
 'Hawker Beechcraft Corporation',
 'CONVAIR',
 'Jihlavan',
 'ZIVKO AERONAUTICS INC',
 'IAI',
 'Diamond Aircraft',
 'Blanik',
 'NANCHANG',
 'Atr',
 'Classic Aircraft Corp.',
 'CZECH SPORT AIRCRAFT A S',
 'CANADAIR LTD',
 'FOUND ACFT CANADA INC',
 'Partenavia',
 'PROGRESSIVE AERODYNE INC',
 'SIAI MARCHETTI',
 'CubCrafters Inc',
 'FLIGHTSTAR INC',
 'MORRISEY',
 'Higher Class Aviation',
 'Forney',
 'I.c.a. Brasov',
 'INTERSTATE',
 'XTREMEAIR GMBH',
 'Piaggio Industrie',
 'AEROSTAR S A',
 'Columbia',
 'Evektor Aerotechnik',
 'Piper/cub Crafters',
 'Omf',
 'AMERICAN GENERAL ACFT CORP',
 'FLIGHTSTAR',
 'Avions Mudry Et Cie',
 'Wsk Pzl Warzawa-okecie',
 'WACO CLASSIC AIRCRAFT CORP',
 'Eagle Aircraft Co.',
 'Eagle',
 'RAINBOW SKY REACH (PTY) LTD',
 'Tecnam',
 'Eclipse Aviation Corporation',
 'Fairchild Dornier',
 'Gulfstream-Schweizer',
 'CUBCRAFTERS',
 'Aerofab Inc.',
 'DASSAULT AVIATION',
 'DASSAULT/SUD',
 'PIPER/CUB CRAFTERS',
 'CESSNA ECTOR',
 'Rotorway',
 'MEYERS INDUSTRIES INC',
 'Twin Commander Acft. Corp.',
 'BEECH AIRCRAFT',
 'Hawker',
 'Eiriavion Oy',
 'AMERICAN CHAMPION',
 'Flugzeugbau',
 'HOWARD AIRCRAFT',
 'MAXAIR',
 'AEROSTAR ACFT CORP OF TEXAS',
 'DASSAULT-BREGUET',
 'Sabreliner Corp.',
 'QUEST',
 'Pzl',
 'American Eurocopter',
 'MX AIRCRAFT LLC',
 'Allied Ag Cat Productions, Inc',
 'Moravan',
 'Piper Aircraft',
 'AVIONS ROBIN',
 'Downer',
 'Remos',
 'TAYLORCRAFT AVIATION CORP.',
 'Cubcrafters',
 'PACIFIC AEROSPACE CORP LTD',
 'General Atomics',
 'SCOTTISH AVIATION',
 'FPNA LLC',
 'Interavia',
 'Rolladen-schneider',
 'ICON AIRCRAFT INC',
 'JUST AIRCRAFT LLC',
 'American Blimp Corp.',
 'NORTH AMERICAN/AERO CLASSICS',
 'Arctic Aircraft Corp.',
 'CONSTRUCCIONES AERONAUTICAS SA',
 'Cessna Aircraft Company',
 'Evektor-Aerotechnik AS',
 'HONDA AIRCRAFT CO LLC',
 'HAWKER BEECHCRAFT CORPORATION',
 'North Wing',
 'Artic Aircraft Corp.',
 'AEROPRO CZ S R O',
 'Eipper',
 'Interplane',
 'ZENAIR LTD',
 'Aerostar International',
 'Costruzioni Aeronautiche Tecna',
 'CIRRUS DESIGN CORPORATION',
 'Piper Aircraft Corporation',
 'AVRO',
 'INIZIATIVE INDUSTRIALI ITALIAN',
 'SKYKITS CORP',
 'KOLB',
 'Hispano Aviacion',
 'Aerostar International Inc.',
 'Flight Design GMBH',
 'S.O.C.A.T.A.',
 'ULTRALIGHT AMERICA',
 'Firefly',
 'PITTS AEROBATICS',
 'FAIRCHILD(HOWARD)',
 'Beagle Aircraft',
 'GRUMMAN AIRCRAFT ENG CORP',
 'Air Creation',
 'JIHLAVAN AIRPLANES SRO',
 'NEW PIPER',
 'QUAD CITY ULTRALIGHT ACFT CORP',
 'TUPOLEV',
 'AVEKO SRO',
 'Airborne',
 'Start & Flug',
 'PPHU EKOLOT',
 'Britten Norman',
 'BEAGLE',
 'DeHavilland',
 'Lindstrand Balloons',
 'Slingsby',
 'Spartan',
 'GULFSTREAM AMERICAN CORP.',
 'GATES LEAR JET CORP.',
 'HAWKER BEECH',
 'Md Helicopter',
 'Meyers Aircraft Co.',
 'AIR CREATION',
 'AEROPRAKT',
 'Avia Stroitel',
 'Howard Aircraft',
 'ZENAIR',
 'Howard Aircraft Corp.',
 'Commander Aircraft Company',
 'Costruzioni Aeronautiche',
 'Beech Aircraft Corporation',
 'Quad City',
 'Brantly',
 'Nord',
 'CHANCE VOUGHT',
 'BELL HELICOPTER TEXTRON CANADA',
 'Rockwell Commander',
 'Aviat Aircraft Inc.',
 'Wsk Pzl',
 'Aerotechnik',
 'EMBRAER S.A.',
 'American Aviation Corp. (AAC)',
 'Piper Aircraft, Inc.',
 'British Aircraft Corp. (bac)',
 'Icon',
 'Curtiss-Wright',
 'Hawker-Beechcraft',
 'VICKERS',
 'FANTASY AIR',
 'Grumman American Aviation',
 'M-SQUARED',
 'Glasflugel',
 'STOL',
 'Challenger',
 'FOUGA',
 'Piper Aerostar',
 'QUICKSILVER MANUFACTURING INC',
 'Piaggio',
 'Grumman Acft Eng',
 'AMERICAN LEGEND',
 'AGUSTA',
 'Rans, Inc.',
 'Golden Circle Air',
 'Adams',
 'McDonnell Douglas',
 'Thrush Aircraft, Inc.',
 'Rans',
 '737',
 'EADS SOCATA',
 'Phantom Aeronautics',
 'CASA',
 'BELCHER WILLIAM B II',
 'FAIRCHILD HELI-PORTER',
 'Westland Helicopters',
 'MONOCOUPE',
 'WSK-PZL WARZAWA-OKECIE',
 'TL Ultralight SRO',
 'GULFSTREAM AM CORP COMM DIV',
 'Monocoupe Aircraft',
 'Lancair Company',
 'TRAVEL AIR',
 'EDGE',
 'NEIVA',
 'Air & Space',
 'M-SQUARED AIRCRAFT',
 'Cosmos',
 'BEECH AIRCRAFT CORPORATION',
 'Aviat Inc',
 'ROBINSON HELICOPTER',
 'CESSNA/AIR REPAIR INC',
 'Waco Classic Aircraft Corp.',
 'NORD',
 'Fantasy Air',
 'Schweizer Aircraft Corp.',
 'American Legend Aircraft Co.',
 'PERTH AMBOY',
 'VARGA AIRCRAFT CORP.',
 'Schweizer Aircraft Corp',
 'CULVER',
 'Liberty',
 'Aviation International Rotors',
 'Erickson',
 'Micco Aircraft Company',
 'BAE SYSTEMS',
 'S C AEROSTAR S A',
 'Czech Aircraft Works SPOL SRO',
 'AIRCRAFT MFG & DVLPMT CO',
 'DORNIER GMBH',
 'KAMAN',
 'Allegro',
 'Canadian Car & Foundry',
 'Scheibe',
 'Varga',
 'HAWKER AIRCRAFT LTD',
 'Gulfstream American Corp.',
 'Glasair',
 'TITAN',
 'Arrow Aircraft Co.',
 'MEUER MARK',
 'Aeropro CZ',
 'Boeing Helicopters Div.',
 'Eclipse Aviation',
 'FUNK',
 'SONEX',
 'Rose',
 'Aerostar International Inc',
 'Mdhi',
 'Ryan Aeronautical',
 'Univar',
 'Eads Socata',
 'Aerostar, S.a',
 'Extra Flugzeugbau Gmbh',
 'Cameron',
 'COLUMBIA',
 'Kolb',
 'Robin',
 'Air Tractor Inc',
 'Quad City Ultralight Aircraft',
 'Raven Industries',
 'AIRPLANE FACTORY (PTY) LTD',
 'Commonwealth',
 'Continental Copters',
 'Siai-Marchetti',
 'ARADO-FLUGZEUGWERKE GMBH',
 'Found Aircraft Canada Inc',
 'Iniziative Industriali Italian',
 'BIRD',
 'QUICKSILVER ENTERPRISES INC',
 'GROB-WERKE',
 'Golden Eagle',
 'Saab-scania',
 'Thunder And Colt',
 'Consolidated-vultee',
 'REIMS AVIATION SA',
 'Classic Aircraft Corp',
 'Short Bros.',
 'Kitfox',
 'AEROFAB INC',
 'Cameron Balloon',
 'CZECH SPORTPLANES SRO',
 'GRUMMAN AMERICAN',
 'MAGNAGHI AERONAUTICA SPA',
 'Gulfstream American Corp',
 'WSK-MIELEC',
 'Pdps Pzl-bielsko',
 'AYRES THRUSH',
 'S.C. Aerostar S.A.',
 'North American Aviation Div.',
 'SKYKITS USA CORP',
 'Md Helicopters, Inc.',
 'Glaser-dirks',
 'VASHON AIRCRAFT',
 'COMMANDER AIRCRAFT CO',
 'Aeroprakt',
 'MIKOYAN GUREVICH',
 'PIPISTREL',
 'AEROS LTD',
 'New Standard',
 'DOWNER',
 'Dassault/sud',
 'Pzl Warzawa-okecie',
 'YAKOVLEV/CHINNERY',
 'WEINZIERL',
 'Palmer',
 'FETTERMAN LANNY R',
 'Fairchild Industries',
 'TL ULTRALIGHT',
 'CONSOLIDATED AERONAUTICS INC',
 'URBAN AIR SRO',
 'AIRTIME AIRCRAFT INC',
 'BOEING COMPANY, LONG BEACH DIV',
 'GIPPSLAND',
 'FOCKE-WULF',
 'BRM AERO',
 'DRAKE',
 'VOLAIRCRAFT',
 'YUNEEC',
 'GLASAIR AVIATION USA LLC',
 'BAE SYSTEMS (OPERATIONS) LIMIT',
 'NORTHWING',
 'FK LIGHTPLANES',
 'PZL OKECIE',
 'L GOLDNER',
 'BROUSSARD',
 'Boeing Commercial Airplane Gro',
 'BELLER',
 'AIRCRAFT MFG & DESIGN LLC',
 'KENNETH M FRANZ',
 'MAXAIR DRIFTER',
 'CESSNA/WEAVER',
 'LITTLE EAGLE',
 'SOFTEX INVEST LLC',
 'BREEZER AIRCRAFT',
 'MARSH AVIATION',
 'Cessna Skyhawk II',
 'P Z L -WARSZAWA-CNPSL',
 'KITFOX',
 'SHORT BROTHERS & HARLAND LTD.',
 'TITAN AEROSPACE HOLDINGS INC',
 'RANS AIRCRAFT',
 'BUHL',
 'FRANKE ROLAND',
 'EIPPER FORMANCE INC',
 'CONSOLIDATED AERONAUTICS',
 'PHANTOM AIRCRAFT CO',
 'SILER RONALD E',
 'ROCKWELL COMMANDER',
 'CITABRIA',
 'WILSON MICHAEL A',
 'SEA & SKY INC DBA KRUCKER ACFT',
 'M7 AEROSPACE LLC',
 'ILYUSHIN',
 'RAYTHEON CORPORATE JETS INC',
 'SHORT BROTHERS PLC',
 'COLONIAL',
 'BRANDT LEROY E',
 'BAILEY-MOYES MICROLIGHTS',
 'DEVOE',
 '3XTRIM',
 'KINNER',
 'BEDECORP LLC',
 'AEROSPOOL',
 'LANSHE AEROSPACE',
 'CGS AVIATION LLC',
 'QUICKSILVER EIPPER ACFT INC',
 'FOXAIR LLC',
 'AMATEUR BUILT AIRCRAFT',
 'HUGHES AERO CORP',
 'AMATEUR CONSTRUCTION',
 'DIAMOND AIRCRAFT INDUSTRIES IN',
 'BARGER JERRY L',
 'CESSNA REIMS',
 'ROBINSON HELICOPTER COMPANY',
 'INDUS AVIATION INC.',
 'SLINGSBY',
 'BOEING 777-306ER',
 'LIBERTY AEROSPACE',
 'SAAB-SCANIA AB',
 'GATES LEARJET',
 'FERDON',
 'FARTHING JAMES W II',
 'PAC',
 'Bombardier Canadair',
 'COLYAER SL',
 'CUB CRAFTER',
 'EIPPER',
 'EAGLE AIRCRAFT CO',
 'WORLD AIRCRAFT CO',
 'FOGG',
 'BARTELS',
 'Seguin',
 'AIRPLANE FACTORY (PTY) LTD THE',
 'SUI RY, LAURINEN JANNE, KÃ„Ã„RIÃ„',
 'Wag-Aero',
 'RANS EMPLOYEE FLYING CLUB',
 'MAULE AIRCRAFT CORP',
 'FACEBOOK UK LTD',
 'QUEST Aircraft Company',
 'BUCKEYE INDUSTRIES',
 'POLLACK',
 'Rainbow Sky Reach',
 'AVIONS MUDRY ET CIE',
 'TUMBLING GOOSE LLC',
 'FRITZ NEUMEYER',
 'CANADIAN CAR & FOUNDRY',
 'BRISTELL',
 'CANADIAN LIGHT ACFT SALES &SVC',
 'S C AEROSTAR S .A.',
 'NORMAN',
 'HOLLEY CAROL L',
 'PARTENAVIA S.P.A.',
 'SABRENA',
 'KESSINGER ROGER L',
 'CESSNA Aircraft',
 '177MF LLC',
 'EVOLUTION TRIKES',
 'GULFSTREAM SCHWEIZER A/C CORP',
 'SCHUMACHER',
 'British Aerospace Civil Aircr',
 'ERICK MAGNO & ASSOC PA',
 'Weatherly Aviation Company Inc',
 'TAYLOR',
 'DOVA AIRCRAFT',
 'AEROFAB INC.',
 'CLARK',
 'COSMOS PHASE II',
 'BUCKER JUNGMEISTER',
 'U-FLY-IT',
 'NAKAJIMA',
 'CONSOLIDATED  AERONAUTICS INC.',
 'BAILEY ROBERT',
 'PHANTOM AERONAUTICS',
 'ECLIPSE AVIATION',
 'KELM DAVID',
 'GOLDEN CIRCLE AIR INC',
 'MCDONNELL DOUGLAS CORPORATION',
 'VIKING AIR LIMITED',
 'BRM AERO SRO',
 'NORTH WING',
 'Schweitzer',
 'Honda Aircraft',
 'GRUMMAN American Corporation',
 'HERRICK DAVID A',
 'BAGLEY CURTIS LYNN',
 'PHOENIX AIR SRO',
 'ERIC A MUNZER',
 'SANTA FE AIRCRAFT LLC',
 'HALL TERRENCE / HALL CATHIE',
 'AVID',
 'RANDAL C REIMER',
 'Cavalier',
 'BEVILACQUA JEFFREY L',
 'ZUBER THOMAS P',
 'CULP JOHN S',
 'DOAN VERNON D',
 'SHARP RALPH R',
 'BACH JOSEPH E',
 'WYDER ROBERT G',
 'Bely',
 'GORDON SCOT A',
 'RAY EARL D',
 'SYRACUSE V F/SYRACUSE C D',
 'Murphy',
 'MCKENZIE JOHN P',
 'FPNA',
 'SACHSE STEPHAN',
 'ADAMS DENNIS ALLEN',
 'PARADISE AIRCRAFT USA LLC',
 'TUTTLE BRUCE C',
 'Honda Jet',
 'Darrell D. Dugger',
 'EMBRAER EXECUTIVE AIRCRAFT INC',
 'MONTE CLARK',
 'JOBY AERO INC',
 'LEACH MICHAEL',
 'WALTER TACHIKI',
 '2021FX3 LLC',
 'Cruiser',
 'American Legend Aircraft Compa',
 'MICHAEL V CRANFORD',
 'Quad City Ultralight',
 'JOEL A BOWKER',
 'FERNANDES DALE R',
 'AVE STEPHEN',
 'Earthstar Aircraft',
 'CURNUTT ELTON E',
 'FERACA EDWARD M',
 'DEWSNUP DAVE',
 'VINING JOHN K',
 'WARE JERRY L',
 'ANTENOR VELAZCO',
 'WESTON JAMES',
 'MAXSON PHIL',
 'PZL Warszawa-Okecie',
 'MCCLURE B J',
 'ROBERT TREMBLY',
 'Legacy',
 'Storm Fury',
 'Ted Smith',
 'MARQUART',
 'ISRAEL AEROSPACE INDUSTRIESLTD',
 'Focke-Wulf',
 'MYRON OLESON',
 'SCOTT MILLS',
 'LITEFLITE PTY LTD',
 'MD HELICOPTER',
 'DIAMOND AIRCRAFT INDUSTRIES',
 'STOUT GARRY V',
 'SUPERMARINE',
 'LORAH ELDEN A',
 'COMCO IKARUS',
 'ALASKAN AIR ADVENTURES LLC',
 'WEISS DENIS',
 'PAYNE STEVEN R',
 'KUYKENDALL CHARLES',
 'Aerospool',
 'KEVIN P STOLHAMMER',
 'TURBINE CUBS OF WYOMING LLC',
 'DEHAVILLAND CANADA',
 'Joplin',
 'BAILEY N MOYES',
 'ROBINSON MICHAEL E',
 'HUGHES',
 'Spitfire',
 'C M STUHRENBERG/P C POLETE',
 'ARTER WARREN',
 'HARTUNIAN ROBERT',
 'Wagaero',
 'MERIWETHER JON',
 'ANGUS WATT',
 'EVEKTOR',
 'JACQUNEAUX GLEN R',
 'KUMHYR DAVID B',
 'WILLIAM L BELL',
 'MCKENNA GLEN R',
 'KNOTT VERNON W',
 'OWEN KINGSLEY B',
 'SUTPHIN JOHN E',
 'STORY CHARLES BRAD',
 'RAY E ROBERTS',
 'FLIGHT DESIGN GENERAL AVN GMBH',
 'Boeing (Stearman)',
 'MARY ALEXANDER',
 'SCODA AERONAUTICA LTDA',
 'AAA AIRCRAFT LLC',
 'BEARHAWK',
 'ORLICAN S R O',
 'JAMES R DERNOVSEK',
 'PHANTOM',
 'DETRICK DONALD G',
 'MULHOLLAND ROBERT A',
 'PIPISTREL D O O',
 'ECLIPSE AEROSPACE INC',
 'SCOTT TERRY G',
 'SEAMAX AIRCRAFT',
 'PERYERA ARNET',
 'BALCOMB KENNETH C III',
 'AEROPRAKT MANUFACTURING SP ZOO',
 'MCGLAUGHLIN RICHARD',
 'EVANS JAMES JAY',
 'KINGERY MICHAEL C',
 'GREEN L/GILNER D',
 'SHORT',
 'ICP SRL',
 'PF CUB FLYERS LLC',
 'C A S A',
 'SHEA',
 'MEYER FRED J',
 'Cessna Aircraft Co.',
 'FOSTER WILLIAM D',
 'VAN LEHN RICHARD GLENN',
 'GRUMMAN AMERICAN AVN. CORP',
 'Sorrel',
 'CO-Z DEVELOPMENT CORP',
 'PYKA INC',
 'SPARKS RALPH A',
 'QUICKSILVER AIRCRAFT CO',
 'WINGREN NORMAN',
 'BLUE SIDE UP INC',
 'SUPERIOR',
 'Kodiak',
 'PIPER-HARRIS',
 'DIETRICH RYAN',
 'AMD',
 'PEPPERD GREG J',
 'CRAWFORD JAMES R',
 'GEIST DONALD R',
 'HOLLAND MIKE',
 'MILLER-THORP',
 'VULCANAIR',
 'UNITED CONSULTANTS',
 'EASTER WILLIAM C',
 'MXR TECHNOLOGIES INC',
 'ARION',
 'Cassult Racer',
 'Hawker Aircraft Ltd',
 'CASSUTT',
 'KAKELDEY RONALD O',
 'Believer',
 'BLACKSHAPE',
 'GMK VENTURES LLC',
 'JAMES C GEYMAN',
 'Bucker',
 'JABIRU AIRCRAFT PTY LTD',
 'MICHAEL J ROBBINS',
 'PITTS SPECIAL',
 'OLIVER LAWRENCE R',
 'Howard',
 'BRYANT FREDERICK M',
 'COLUMBIA AIRCRAFT Mfg',
 'HALLADAY ROY',
 'HARBIN',
 'STEEN',
 'MICROLITES PTYLTD',
 'APOLLO AIRCRAFT INC',
 'Curtiss Wright',
 'ROSE',
 'Travel Air',
 'RGJ AVIATION LLC',
 'GIPPSAERO PTY LTD',
 'LITE FLIGHT',
 'FAIRCHILD FUNK',
 'FLIGHTWORKS CORP',
 'SOKO',
 'Siai Marchetti',
 'Airplane Factory',
 'ULTRALITE SRO',
 'JM Kemp',
 'AIRvan',
 'SKYBolt',
 'Howard Steven C',
 'DAVID S MEEK',
 'S.A.N.',
 'RATHEON AIRCRAFT COMPANY',
 'Vought',
 'Gippsland',
 'Zlin',
 'STORCH',
 'BARROWS',
 'NORTHROP',
 'MORAVAN',
 'STOL Aircraft Corp',
 'BRM Aero',
 'Czech Sport',
 'BEECH AIRCRAFT CO.',
 'QUARTZ MOUNTAIN AEROSPACE',
 'ICON',
 'Zodiac',
 'CHICCO MIGUEL E',
 'SLIP STREAM',
 ...]

In [73]:
modellist = list(newdf['Model'].value_counts().index)

In [74]:
modellist

['172',
 '152',
 '737',
 '172N',
 '172S',
 '182',
 '172M',
 'PA-28-140',
 'SR22',
 '180',
 'PA28',
 'A36',
 'PA-18-150',
 '172P',
 '150',
 'PA-28-180',
 'PA-28-161',
 'PA-18',
 'PA-28-181',
 '170B',
 '140',
 '172R',
 '208B',
 'M20J',
 '182P',
 'A185F',
 'G-164B',
 '210',
 '150M',
 '7GCBC',
 '7AC',
 '150L',
 'PA-12',
 '58',
 '182Q',
 'PA-24-250',
 '177',
 'PA-32-300',
 'PA-28R-200',
 'PA-30',
 'PA-31-350',
 'M20C',
 'SR20',
 '7ECA',
 'PA-22-150',
 '172RG',
 'A320',
 '777',
 '172K',
 'J3C-65',
 'T210N',
 '185',
 '8A',
 'A188B',
 'P210N',
 'PA18',
 '170',
 '177RG',
 'M20K',
 'G-164A',
 '206',
 '206B',
 '208',
 '150F',
 '120',
 '35',
 '747',
 'PA-38-112',
 'PA-23-250',
 '182A',
 'T210M',
 'AT-301',
 'PA-25-235',
 'PA-28-235',
 'R182',
 'PA-34-200T',
 '172H',
 'PA-32-260',
 'U206G',
 'PA28R',
 '150G',
 '8GCBC',
 'C23',
 'PA-32R-300',
 '207',
 'T210L',
 'A185',
 'S2R',
 '172L',
 '269C',
 '150H',
 '8KCAB',
 'PA32',
 'V35B',
 'M20E',
 'AT-502B',
 'DHC-2',
 '108',
 '767',
 'TR182',
 '200',
 'PA 18-150',
 'PA46',
 'A-1B',
 'PA-28-151',
 '175',
 'PA-44-180',
 'R44',
 '150J',
 '170A',
 'U206',
 '340A',
 'PA-46-310P',
 '369D',
 '195',
 '177B',
 'T210',
 'S-2R',
 'F33A',
 'BC12-D',
 '172F',
 '415-C',
 '757',
 'CL-600-2B19',
 'PA-46-350P',
 'PA34',
 'AT-602',
 'PA-28R-180',
 '182S',
 'M20F',
 '8',
 '182T',
 '421C',
 'PA22',
 'T206H',
 '17-30A',
 'PA-20',
 'V35',
 '310R',
 'PA-22-160',
 'PA-22',
 '340',
 'R22 Beta',
 'PA-32R-301T',
 '182R',
 '180H',
 'U206F',
 '7KCAB',
 'AT-502',
 '210L',
 '95-B55',
 '7GCAA',
 'A-1',
 '36',
 '402C',
 'PA-24-260',
 'R172K',
 'PA-32R-301',
 'C90',
 '550',
 '182J',
 '310',
 'AT502',
 '108-3',
 'A75N1(PT17)',
 '414',
 'B36TC',
 'B200',
 'PA32R',
 'PA24',
 '421B',
 'CTSW',
 'T182T',
 '11AC',
 'A330',
 'PA 12',
 'A36TC',
 'AA-5A',
 'PA 46-350P',
 'AA-5B',
 'M20M',
 '76',
 'S2R-T34',
 '402B',
 '1900D',
 '525',
 'TBM 700',
 '172G',
 'J3C',
 '35A',
 '172E',
 'PA-18-135',
 '407',
 'PA-34-220T',
 'M20R',
 'PA25',
 'AT-802A',
 'PA-28',
 '560',
 'GC-1B',
 'CTLS',
 '305A',
 '737-800',
 '182G',
 'SR-22',
 'S35',
 '23',
 'PA-34-200',
 '421',
 '180J',
 'AT-401',
 'G164',
 '108-1',
 'A188',
 '180K',
 '182K',
 'PA 28-140',
 'B75N1',
 '182C',
 '500',
 '7EC',
 'PA 28-180',
 'PA-22-135',
 '185F',
 'DA 40',
 '182L',
 'R-22',
 'PA23',
 '402',
 '182H',
 '172B',
 'CC11-160',
 'R22',
 '182M',
 'P210',
 '182E',
 'PA-32RT-300',
 'TU206G',
 '206L-1',
 'R-44',
 '207A',
 'NAVION',
 '100',
 'PA31',
 'A185E',
 '8E',
 'PA-32-301',
 'M-18A',
 'PA 18',
 'DA 20-C1',
 'PA-22-108',
 '182D',
 'A75N1',
 '787',
 'G35',
 'PA 28-181',
 '58P',
 '206L-3',
 'A23',
 '108-2',
 '560XL',
 '182B',
 'AT 602',
 '441',
 '180A',
 'PA-24',
 '310Q',
 'MD-82',
 'T188C',
 'K35',
 'C24R',
 'PA 28',
 'T310R',
 '182F',
 'G-164',
 'M20',
 '55',
 '737-300',
 'PA-23-160',
 'PA-46-500TP',
 '188',
 '162',
 'PA-28R-201',
 'C35',
 'AA-5',
 'PA-32RT-300T',
 '150K',
 '114',
 'AA-1',
 'PA-28-236',
 'EMB-145LR',
 '172D',
 '172C',
 'PA38',
 '172A',
 'B19',
 'AT802',
 'SPORTSTAR',
 'A1',
 'E75',
 '717-200',
 'LA-4-200',
 'R-22B',
 '369E',
 'AT 502',
 'M-5-235C',
 '7BCM',
 'UH-1H',
 'H35',
 '415',
 'G36',
 'A321',
 'TU206',
 'PA 30',
 'PA-28-160',
 '210N',
 '150E',
 '1900C',
 'ERJ190',
 'PA-16',
 '501',
 '182N',
 'J5A',
 '210M',
 'DHC-3',
 'PA-11',
 'AT 502B',
 '1900',
 'PA32RT',
 'PA 28-161',
 'A-1C-180',
 '737-7H4',
 'DA20',
 'MX7',
 'SR22T',
 '188B',
 '747-400',
 '60',
 'PA 24-250',
 'AA-1B',
 '150D',
 'PA-24-180',
 'AA-1A',
 '414A',
 'PA-28RT-201',
 'A319',
 '620B',
 '737-200',
 'YAK 52',
 'AA5',
 'PA-28R-201T',
 '172I',
 'EA 300/L',
 'LC41-550FG',
 'AL3',
 'PA-31T',
 'F33',
 '172SP',
 '77',
 'F19',
 'M35',
 'PA-18-160',
 'P35',
 '212',
 'A320-232',
 'H-295',
 'PA-18A',
 'SPORTCRUISER',
 'ST3KR',
 '737 7H4',
 '95-B55 (T42A)',
 '35-B33',
 '210A',
 'P206',
 'R-22 Beta',
 'D35',
 '195A',
 '7FC',
 'M-4-220C',
 '8F',
 'M20TN',
 '305',
 '737-400',
 'PA46-500TP',
 'A35',
 'MD-11',
 'V35A',
 '210E',
 '269C-1',
 'MD-83',
 'M-5-210C',
 '269A',
 '2T-1A-2',
 'PA-28RT-201T',
 'R22 BETA',
 '112',
 'OH-6A',
 'C90A',
 'PA-25-260',
 'SA227',
 'PA-14',
 '310N',
 '206H',
 'DA20-C1',
 '15AC',
 'F35',
 'A2',
 'G 164B',
 '757-200',
 'A-1A',
 '99',
 '390',
 'M7',
 '400A',
 'PA-34',
 '337',
 '737-700',
 'MD11',
 'E-55',
 '140A',
 '401',
 'G-IV',
 'AT-402B',
 'M5',
 '690',
 '95B55',
 '337G',
 'PA-36-285',
 'PA 22',
 'PA-18A-150',
 '425',
 'S2R-G6',
 '35-C33',
 'R172E',
 '150C',
 'CHALLENGER II',
 'CL-600-2C10',
 'PA-31-310',
 'CH 2000',
 'T207A',
 'M-7-235',
 'M-7-235C',
 'MU-2B-60',
 '95-C55',
 'PA 28R-200',
 '175A',
 'PA 25-235',
 'S2R-G10',
 '757-232',
 'DC-3',
 '525A',
 'DHC8',
 'F-28C',
 '412',
 'PC12',
 'PA-31P',
 'PA-31',
 'PA30',
 '369HS',
 'PA-32',
 'PA-31-325',
 'S 2R',
 '210D',
 'BE-58',
 'PA 32-300',
 'OH-58A',
 '182RG',
 'EMB145',
 '601P',
 'UPF-7',
 '47G-3B-1',
 'N35',
 'A100',
 '47G-2',
 'T303',
 'J35',
 '95',
 'PA-32R',
 'A-1C-200',
 'SA227-AC',
 'PC-12/45',
 'UH-12E',
 'AT-402A',
 'PA28-140',
 'DC-10-30',
 'A220',
 'F172',
 'E-90',
 '210K',
 '112A',
 'PA-25',
 'R172',
 'T-28B',
 'RV-12',
 '650',
 'T182',
 'CL-600',
 'AS350BA',
 'T337G',
 'DA 20 C1',
 'BE-55',
 'B35',
 'AT-400',
 '175B',
 'A-36',
 'MX-7-235',
 'G 164A',
 '404',
 '177A',
 '400',
 'J-3',
 'PA-23',
 '206-L4',
 'SNJ-5',
 'AA1',
 'F90',
 'M-5-180C',
 '757-222',
 'DHC 2',
 'SR-20',
 '7CCM',
 '320',
 'E162',
 'A23-24',
 'DHC2',
 'CL600 2D24',
 'PA 46 350P',
 'M20S',
 '45',
 'AT-6D',
 '47G',
 '415-D',
 'M20B',
 'DCO-65',
 '690B',
 '210B',
 'A300',
 '310J',
 '195B',
 'BE-23',
 'LAKE LA-4-200',
 '767-300',
 'PA-18A 150',
 'AA-1C',
 'LC41',
 '35-A33',
 'CC18-180',
 '300',
 'Navion',
 'R-22 BETA',
 'EC120B',
 'R44 II',
 'P180',
 'EA500',
 'BC12',
 'BE-76',
 'S2',
 '310C',
 'B100',
 'PA-60-601P',
 'MD-88',
 'PA60',
 'DC-9-82',
 'T206',
 '206B3',
 'MD-11F',
 'MXT-7-180A',
 'Pitts S-2B',
 'PIPER SPORT',
 '201B',
 '510',
 'TU206F',
 'PITTS S-2B',
 'AT 802',
 '19A',
 'BE-200',
 '680',
 'PA 22-150',
 'A 1',
 'S-1B2',
 'M20A',
 'PA-18-105',
 'DHC-6',
 'D55',
 'S-2B',
 'PA 16',
 '757-223',
 '727',
 'LC42-550FG',
 'PA 32R-300',
 'TB-20',
 'J3C 65',
 'PA-32-301T',
 'ATR72',
 'T210K',
 'DA40',
 'PA-18-180',
 'PA36',
 '690A',
 'PA 18-135',
 'M20D',
 'T210G',
 '269D',
 '415C',
 'U206E',
 '185E',
 'R22B',
 '340B',
 '205',
 'M-6-235',
 'PA 20',
 'CL-600-2B16',
 'CL600 2B19',
 '95-A55',
 '500S',
 '65-A90',
 'RC-3',
 '747-200',
 'A45',
 '7DC',
 'AT-402',
 '190',
 'OH-58C',
 '747-422',
 '112TC',
 'BE-36',
 '25B',
 'REMOS GX',
 'T188',
 'A75N1 (PT17)',
 'PA 18A 150',
 '737-3H4',
 'M-7-235B',
 'DC3',
 'EMB-500',
 'E18S',
 'SA226TC',
 'PA-22/20',
 '95-55',
 'PA-28R',
 'AT 301',
 'B60',
 'A75',
 '737-823',
 '7GCB',
 'A 1B',
 '737-500',
 'BEAVER DHC 2',
 'PA-36-300',
 'K-1200',
 '180D',
 'BE-35',
 'T207',
 'S2R-600',
 'G58',
 '33',
 'Aerostar 601P',
 'DHC-6-300',
 '737-8H4',
 '7GC',
 'E90',
 'G-164C',
 'P-51D',
 'B24R',
 'B300',
 '310K',
 'CL 600 2C10',
 'CC11-100',
 '25',
 'BC12 D',
 'T337',
 '415 C',
 'PA 24',
 '369FF',
 'PA 28R-201',
 'PA-46',
 'T-28C',
 'B90',
 '180B',
 '19',
 'AT602',
 '65',
 'PA-18-105 SPECIAL',
 'LA-4',
 'B737-400',
 '180G',
 'LUSCOMBE 8A',
 'A188A',
 '787-9',
 'YMF-F5C',
 'DC-9-83',
 'T-6G',
 '210F',
 'SA-226T',
 'B75',
 '320E',
 'PA-31T1',
 'GIV',
 'BOEING 737-8AS',
 'ATR42',
 'DHC-2 MK. I(L20A)',
 '2150A',
 '210C',
 '1124',
 'L-39C',
 'PA 11',
 '777-222',
 'G-44',
 'A321 231',
 'D17S',
 '2000',
 'A60',
 'B-60',
 'AT-802',
 'PA44',
 '95 B55 (T42A)',
 '17 30',
 'M-20J',
 '180C',
 'AS-350-B2',
 '757-251',
 'B-2B',
 'A319-111',
 '47G-4A',
 '500-S',
 '150A',
 '737-824',
 'J230-SP',
 'CL600 2C10',
 'CHALLENGER',
 'G 164',
 'AT402',
 '551',
 'HA-420',
 'H 295',
 'GC 1B',
 'PA 28-235',
 '337C',
 'DC-9-51',
 'MD88',
 '310L',
 '411',
 'NAVION A',
 'E35',
 'PA 18A',
 'PA-15',
 '310F',
 'SNJ-6',
 'B23',
 'P2002 SIERRA',
 'AEROSTAR 601P',
 'J3-C65',
 'MT-7-235',
 '269B',
 'P2004 BRAVO',
 'PA-28-150',
 '777-223',
 'SA226',
 'BN2A',
 'MD80',
 '500-B',
 '310I',
 'TBM700',
 'P337H',
 'EMB-120ER',
 'PA 22-160',
 'PA 28R-201T',
 '210G',
 'AA 5',
 'SPORTSTAR PLUS',
 '750',
 'DA-40',
 'A-1C',
 'SNJ',
 'D95A',
 'S12',
 'DHC-8-402',
 'PA 28R-180',
 'EMB-135LR',
 '737-524',
 'MQ-9',
 'AT-6C',
 'PA 23-250',
 'LC41 550FG',
 'DHC6',
 'PA46R-350T',
 'BC12-65',
 'TB10',
 'PA-39',
 'A320-211',
 'AA 1',
 '525B',
 '1730',
 'PA28-151',
 'SF50',
 'DRAGONFLY',
 '737-832',
 'T210F',
 'U206C',
 'S2R-T15',
 'PA 31-350',
 'T28',
 'DA42',
 '206L',
 '210-5(205)',
 'B737-300',
 'J3',
 'AS350B3',
 'L39C',
 'MXL II',
 'PA46 500TP',
 'Navion A',
 'AA1B',
 'S2R-H80',
 'J3F-65',
 'A330-323',
 'STINGSPORT',
 'XL-2',
 'PC-12',
 'B737-800',
 'MX-7-180A',
 'CH2000',
 '35-33',
 '401A',
 'DC-9-31',
 'A23A',
 '767-332',
 '17-30',
 'C-99',
 'UH-1B',
 'ERJ 170-200 LR',
 '114-B',
 '502B',
 'F150',
 '727-200',
 'DR400',
 'A150M',
 'BEAVER DHC-2 MK.1',
 'SGS 2-33A',
 'HAWKER',
 '210J',
 '369A',
 'AS-350BA',
 'F-19',
 'M-4-210C',
 'R22 Beta II',
 '14-19',
 'MU-2B-40',
 'AA 5B',
 'PA-36-375',
 'T210R',
 'Sport Cruiser',
 'DA 40 NG',
 'A150L',
 'DHC-8-102',
 '500 S',
 'T210J',
 '206G',
 'T210H',
 '310D',
 'E33A',
 'D18S',
 'AT-502A',
 '320D',
 '180F',
 'UH-12B',
 'PA 46',
 '35-C33A',
 'A23-19',
 'BL-17-30A',
 'WACO YMF',
 'B95',
 '201C',
 '777-200',
 'PC-12/47E',
 'TIGER MOTH DH 82A',
 'G-21A',
 'MU2B',
 'BD-100-1A10',
 'A24R',
 '200D',
 'ASW-20',
 'PA32-300',
 'A5',
 'AEROSTAR601',
 'TB20',
 'PA28-181',
 'PA 28R',
 'PA-60-602P',
 'MU-2B-35',
 '737-322',
 '280FX',
 'CL 600 2B19',
 'DHC-3T',
 'E55',
 '310P',
 '750XL',
 'CCX-2000',
 'A320-214',
 'G IV',
 'E75N1',
 'PA-20-135',
 'PA-38',
 'MU-2B-36',
 '747-200F',
 'PA-42',
 '300C',
 'Navion G',
 'II',
 '24',
 'J3L-65',
 'DC-3C',
 'PA 34',
 'PA-23-150',
 'M-4',
 'AT 402',
 'Lake LA-4-200',
 'S6',
 'KODIAC 100',
 'PA 31P',
 'S2R-T660',
 'AT-6',
 'PA28RT',
 'AT 402B',
 'AT 401',
 'B737',
 'F-35',
 'PA31T',
 'M18',
 'AT-401B',
 'S-1A',
 '777 223',
 'GULFSTREAM AM G-164B',
 'MU-2B-26A',
 'PA12',
 'PA 32R-301T',
 'A',
 'EMB120',
 'FH-1100',
 'PA 28-236',
 '600N',
 'CJ-6A',
 '228',
 'B-55',
 'P92 EAGLET',
 'M-7-260C',
 '767-300ER',
 'AT-400A',
 'G164B',
 'C24',
 'BE-60',
 '280C',
 '185A',
 'ERJ170-200LR',
 '737-724',
 'EA-300',
 'F172N',
 'S550',
 '58TC',
 '310B',
 'UPF 7',
 'A150K',
 'DA 42',
 '350',
 'DHC-8-202',
 'H-18',
 'AG5B',
 'DC-8-71F',
 'HIGHLANDER',
 'AT-4 LSA',
 'CL600-2B19',
 '17-31ATC',
 'PA 34-220T',
 'LA4',
 'LIGHTNING LS-1',
 'L-13',
 'DA 20',
 'PA-28-201T',
 'A119',
 'L-19E',
 'U206B',
 'L19',
 'AT301',
 'YMF',
 '188A',
 'Travel Air 4000',
 'M-7-260',
 'Blanik L-13',
 'RV4',
 '50',
 '47G-5',
 'BT-13A',
 'PA 32R',
 'Sportcruiser',
 'EMB-505',
 'DGA-15P',
 'A-22 VALOR',
 '8C',
 'DHC-6-200',
 '206B-III',
 ...]

In [75]:
newdf['Engine.Type'].value_counts()

Engine.Type
Reciprocating      22806
Turbo Prop          1839
Turbo Fan           1375
Turbo Shaft          652
Turbo Jet            266
Unknown              203
Geared Turbofan       12
Electric               5
UNK                    1
Name: count, dtype: int64

In [76]:
df['Engine.Type'].value_counts()

Engine.Type
Reciprocating      69530
Turbo Shaft         3609
Turbo Prop          3391
Turbo Fan           2481
Unknown             2051
Turbo Jet            703
Geared Turbofan       12
Electric              10
LR                     2
NONE                   2
Hybrid Rocket          1
UNK                    1
Name: count, dtype: int64

In [77]:
df['Broad.phase.of.flight'].value_counts()

Broad.phase.of.flight
Landing        15428
Takeoff        12493
Cruise         10269
Maneuvering     8144
Approach        6546
Climb           2034
Taxi            1958
Descent         1887
Go-around       1353
Standing         945
Unknown          548
Other            119
Name: count, dtype: int64

In [78]:
newdf['Weather.Condition'].value_counts()

Weather.Condition
VMC    26582
IMC     1980
Unk      215
UNK       54
Name: count, dtype: int64

In [79]:
newdf['Air.carrier'].value_counts()

Air.carrier
Pilot                           175
American Airlines                50
Delta Air Lines                  43
SOUTHWEST AIRLINES CO            42
United Airlines                  41
                               ...
China Cargo Airlines              1
Frost Flying Service              1
U.S. Airways, Inc.                1
ROSE RESOURCES OIL & GAS INC      1
MC CESSNA 210N LLC                1
Name: count, Length: 9109, dtype: int64

In [80]:
newdf['Schedule'].value_counts()

Schedule
SCHD    2190
NSCH    1850
UNK      212
Name: count, dtype: int64

In [81]:
newdf['Number.of.Engines'].value_counts()

Number.of.Engines
1.0    23538
2.0     4682
4.0      139
0.0      124
3.0       90
8.0        1
6.0        1
Name: count, dtype: int64

In [82]:
newdf['Investigation.Type'].value_counts()

Investigation.Type
Accident    30445
Incident     2184
Name: count, dtype: int64

In [83]:
df['Aircraft.damage'].value_counts()

Aircraft.damage
Substantial    64148
Destroyed      18623
Minor           2805
Unknown          119
Name: count, dtype: int64

In [84]:
df['Country'].value_counts()

Country
United States                       82248
Brazil                                374
Canada                                359
Mexico                                358
United Kingdom                        344
                                    ...
Seychelles                              1
Palau                                   1
Libya                                   1
Saint Vincent and the Grenadines        1
Turks and Caicos Islands                1
Name: count, Length: 219, dtype: int64

In [85]:
df['Airport.Name'].value_counts()

Airport.Name
Private                           240
PRIVATE                           224
Private Airstrip                  153
NONE                              146
PRIVATE STRIP                     111
                                 ...
STEHEKIN                            1
OTTAWA MUNICIPAL                    1
DWIGHT AIRPORT                      1
PHOENIX DEER VALLEY MUNI            1
WICHITA DWIGHT D EISENHOWER NT      1
Name: count, Length: 24870, dtype: int64

In [86]:
df['Airport.Name'].isna().sum()

36185

In [87]:
df['Purpose.of.flight'].value_counts()

Purpose.of.flight
Personal                     49448
Instructional                10601
Unknown                       6802
Aerial Application            4712
Business                      4018
Positioning                   1646
Other Work Use                1264
Ferry                          812
Aerial Observation             794
Public Aircraft                720
Executive/corporate            553
Flight Test                    405
Skydiving                      182
External Load                  123
Public Aircraft - Federal      105
Banner Tow                     101
Air Race show                   99
Public Aircraft - Local         74
Public Aircraft - State         64
Air Race/show                   59
Glider Tow                      53
Firefighting                    40
Air Drop                        11
ASHO                             6
PUBS                             4
PUBL                             1
Name: count, dtype: int64

In [92]:
df['Make'] = df['Make'].str.upper()
df['Model'] = df['Model'].str.upper()

df['Make'] = df['Make'].str.replace('[^a-zA-Z0-9]', '')
df['Model'] = df['Model'].str.replace('[^a-zA-Z0-9]', '')

df['Make'] = df['Make'].str.replace('-', '')
df['Make'] = df['Make'].str.replace('(', '')
df['Make'] = df['Make'].str.replace(')', '')
df['Model'] = df['Model'].str.replace('-', '')
df['Model'] = df['Model'].str.replace('(', '')
df['Model'] = df['Model'].str.replace(')', '')

In [93]:
df['Model'].head(40)

0                1083
1             PA24180
2                172M
3                 112
4                 501
5                 DC9
6                 180
7                 140
8                401B
9         NAVION L17B
10            PA28161
11               V35B
12              1730A
13              R172K
14                  A
15                 19
16               280C
17                180
18                172
19    WCS222 BELL 47G
20                152
21               150L
22              206L1
23            PA24180
24               AA5B
25               414A
26               BE58
27             M5235C
28               210L
29              7GCBC
30                182
31              AT301
32            PA28161
33           PA34200T
34              T337G
35           PA28R200
36                206
37                  A
38               PA22
39               PA31
Name: Model, dtype: object